config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#index"
  get "/about", to: "pages#about"
  get "/cart", to: "pages#cart"
  get "/care", to: "pages#care"
  patch "/order", to: "pages#order"
  get "/thankyou", to: "pages#thankyou"
  resources :categories
  resources :products
  resources :blogs
  resources :instructions

  # admin side
  namespace :admin do
    root to: "admin#index"
    resources :products
    resources :categories
    resources :users, only: [:index]
    resources :banners
    resources :videos
    resources :blogs
    resources :instructions
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: [:slugged, :finders]
    mount_uploader :homepage_banner, ImageUploader

    has_many :products, dependent: :destroy

    def count_by_id(id)
        @category = Category.find id
        @category.products.count
    end

    def get_some_products(category_id, number = 4)
        @category = Category.find category_id
        @category.products.take number
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
    before_action :set_category, only: [:edit, :update, :show, :destroy]
    
    def index
        @categories = Category.paginate(:page => params[:page], :per_page => 10)
    end

    def new 
        @category = Category.new
    end

    def create
        @category = Category.new category_params
        if @category.save
            flash[:success] = "Created successfully!!"
            redirect_to admin_categories_path
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @category.update_attributes category_params
            flash[:success] = "Updated!!"
            redirect_to admin_categories_path
        else
            render :edit
        end
    end

    def destroy
        if @category.destroy
            flash[:success] = "Deleted!!"
            redirect_to admin_categories_path
        end
    end

    private
    def category_params
        params.require(:category).permit(:title, :homepage_banner)
    end

    def set_category
        @category = Category.find params[:id]
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show]

    def show
        @categories = Category.all
        @products_of_category = @category.products.paginate(:page => params[:page], :per_page => 10)
        @new_products = Product.order(created_at: :desc).take 3
    end

    private
    def set_category
        @category = Category.find params[:id]
    end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= @category.errors.full_messages.first if @category.errors.any? %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :homepage_banner %>
    <%= f.file_field :homepage_banner %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <%= link_to "Back", :back, class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, "Edit category" %>
<% provide :button_text, "Edit" %>

<%= content_for :content do %>
    <h1>Edit category</h1>
    <%= render 'form' %>
<% end %>

app/views/admin/categories/index.html.erb
<% content_for :content do %>
    <div style="padding-top: 10px">
        <%= link_to "Add new category", new_admin_category_path, class: "btn btn-primary" %>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Homepage banner</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <td><%= category.id %></td>
                    <td><%= category.title %></td>
                    <td><%= image_tag category.homepage_banner.url, alt: "homepage banner", width: "200px", class: "img-fluid" %></td>
                    <td>
                      <%= link_to edit_admin_category_path(category), class:"btn btn-primary btn-sm" do %>
                          <span class="fa fa-pencil"></span>
                          Edit
                      <% end %>
                      <%= link_to admin_category_path(category), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-danger btn-sm" do %>
                          <span class="fa fa-trash"></span>
                          Delete
                      <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= will_paginate @categories %>
<% end %>

app/views/admin/categories/new.html.erb
<% provide :title, "Create new category" %>
<% provide :button_text, "Create" %>

<%= content_for :content do %>
    <h1>Create new category</h1>
    <%= render 'form' %>
<% end %>