config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#index"
  get "/about", to: "pages#about"
  get "/cart", to: "pages#cart"
  get "/care", to: "pages#care"
  patch "/order", to: "pages#order"
  get "/thankyou", to: "pages#thankyou"
  resources :categories
  resources :products
  resources :blogs
  resources :instructions

  # admin side
  namespace :admin do
    root to: "admin#index"
    resources :products
    resources :categories
    resources :users, only: [:index]
    resources :banners
    resources :videos
    resources :blogs
    resources :instructions
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]

    belongs_to :category, foreign_key: "category_id"

    mount_uploaders :images, ImageUploader

    def get_saleoff_price
        if self.sale_off > 0
            self.sale_off
        else
            self.price
        end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
    before_action :set_product, only: [:edit, :update, :show, :destroy]
    def index
      if params[:cate_id].to_i != 0
        @category = Category.find params[:cate_id]
        @products = @category.products.paginate(:page => params[:page], :per_page => 10)
      else
        @products = Product.paginate(:page => params[:page], :per_page => 10)
      end
    end

    def new
      @product = Product.new
    end
  
    def create
      @product = Product.new product_params
      if product_params[:images]
        add_more_images(product_params[:images])
      end
      if @product.save
        flash[:success] = "Added!"
        redirect_to admin_products_path
      else
        render :new
      end
    end

    def edit
    end
  
    def update
      if product_params[:images]
        @product.images = []
      end
      if @product.update_attributes product_params
        flash[:success] = "Updated!!"
        redirect_to admin_products_path
      else
        render :edit
      end
    end
  
    def destroy
      if @product.destroy
        flash[:success] = "Deleted!"
        redirect_to admin_products_path
      end
    end

    private
    def product_params
      params.require(:product).permit(:name, :description, :price, {images: []}, :category_id, :information, :sale_off, :expired_date)
    end

    def set_product
      @product = Product.find params[:id]
    end

    def add_more_images(new_images)
      images = @product.images
      images += new_images
      @product.images = images
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product = Product.find params[:id]
        @other_products = Product.order("RANDOM()").take 6
        @blogs = Blog.all.take(15)
    end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| %>
  <%= @product.errors.full_messages.first if @product.errors.any? %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "editor form-control", rows: 10 %>
  </div>

  <div class="form-group">
    <%= f.label :information %>
    <%= f.text_area :information, class: "editor form-control", rows: 20 %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
  </div>

  <div class="form-group">
    <%= f.label :sale_off_price %>
    <%= f.number_field :sale_off, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "expired_date (Nếu có sale off thì phải nhập ngày hết hạn)" %>
    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
      <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
    </div>
  </div>

  <% if @product.persisted? %>

    <div class="form-group">
      <%= f.label :category %>
      <%= f.select :category_id, options_for_select(Category.all.map{ |c| [c.title, c.id] }, selected_key = f.object.category_id) %>
    </div>

  <% else %>

    <div class="form-group">
      <%= f.label :category %>
      <%= f.select :category_id, Category.all.map { |category| [category.title, category.id] }, :prompt => 'Select One' %>
    </div>

  <% end %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <%= link_to "Back", :back, class: "btn btn-primary" %>
<% end %>

<%= tinymce :alternate %>

app/views/admin/products/edit.html.erb
<% provide :title, "Edit product" %>
<% provide :button_text, "Update" %>

<%= content_for :content do %>
    <h1>Edit product</h1>
    <%= render 'form' %>
<% end %>

app/views/admin/products/index.html.erb
<% content_for :content do %>
    <div style="padding-top: 10px">
        <%= link_to "Add new product", new_admin_product_path, class: "btn btn-primary" %>
    </div>
    <div style="padding-top: 10px">
        <p>Categories Filter</p>
        <form>
            <select name="cate_id">
              <option value="0">--None--</option>
              <% Category.all.each do |category| %>
                <% if @category && @category.id == category.id %>
                  <option value="<%= category.id %>" selected><%= category.title %></option>
                <% else %>
                  <option value="<%= category.id %>"><%= category.title %></option>
                <% end %>
              <% end %>
            </select>
            <input type="submit">
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Categories</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @products.each do |product| %>
                <tr>
                    <td><%= product.id %></td>
                    <td><%= product.name %></td>
                    <td><%= product.category.title %></td>
                    <td>
                      <%= link_to admin_product_path(product), class:"btn btn-primary btn-sm" do %>
                          <span class="fa fa-eye"></span>
                          Show
                      <% end %>
                      <%= link_to edit_admin_product_path(product), class:"btn btn-primary btn-sm" do %>
                          <span class="fa fa-pencil"></span>
                          Edit
                      <% end %>
                      <%= link_to admin_product_path(product), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-danger btn-sm" do %>
                          <span class="fa fa-trash"></span>
                          Delete
                      <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= will_paginate @products %>
<% end %>

app/views/admin/products/new.html.erb
<% provide :title, "Create new product" %>
<% provide :button_text, "Create" %>

<%= content_for :content do %>
    <h1>Create new product</h1>
    <%= render 'form' %>
<% end %>

app/views/admin/products/show.html.erb
<% content_for :content do %>
  <p><strong>Name: </strong></p>
  <%= @product.name %>
  <br /><br />

  <p><strong>Description: </strong></p>
  <%= @product.description.html_safe %>
  <br /><br />

  <p><strong>Information: </strong></p>
  <%= @product.information.html_safe %>
  <br /><br />

  <p><strong>Price: </strong></p>
  <%= number_to_currency @product.price %>
  <br /><br />

  <p><strong>Images: </strong></p>
  <% @product.images.each do |image| %>
    <%= image_tag image.url, height: "220px" %>
  <% end %>
  <br /><br />

<% end %>