config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#index"
  get "/about", to: "pages#about"
  get "/cart", to: "pages#cart"
  get "/care", to: "pages#care"
  patch "/order", to: "pages#order"
  get "/thankyou", to: "pages#thankyou"
  resources :categories
  resources :products
  resources :blogs
  resources :instructions

  # admin side
  namespace :admin do
    root to: "admin#index"
    resources :products
    resources :categories
    resources :users, only: [:index]
    resources :banners
    resources :videos
    resources :blogs
    resources :instructions
  end
  
end

app/models/product.rb
class Product < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: [:slugged, :finders]

    belongs_to :category, foreign_key: "category_id"

    mount_uploaders :images, ImageUploader

    def get_saleoff_price
        if self.sale_off > 0
            self.sale_off
        else
            self.price
        end
    end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
    before_action :set_product, only: [:edit, :update, :show, :destroy]
    def index
      if params[:cate_id].to_i != 0
        @category = Category.find params[:cate_id]
        @products = @category.products.paginate(:page => params[:page], :per_page => 10)
      else
        @products = Product.paginate(:page => params[:page], :per_page => 10)
      end
    end

    def new
      @product = Product.new
    end
  
    def create
      @product = Product.new product_params
      if product_params[:images]
        add_more_images(product_params[:images])
      end
      if @product.save
        flash[:success] = "Added!"
        redirect_to admin_products_path
      else
        render :new
      end
    end

    def edit
    end
  
    def update
      if product_params[:images]
        @product.images = []
      end
      if @product.update_attributes product_params
        flash[:success] = "Updated!!"
        redirect_to admin_products_path
      else
        render :edit
      end
    end
  
    def destroy
      if @product.destroy
        flash[:success] = "Deleted!"
        redirect_to admin_products_path
      end
    end

    private
    def product_params
      params.require(:product).permit(:name, :description, :price, {images: []}, :category_id, :information, :sale_off, :expired_date)
    end

    def set_product
      @product = Product.find params[:id]
    end

    def add_more_images(new_images)
      images = @product.images
      images += new_images
      @product.images = images
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def show
        @product = Product.find params[:id]
        @other_products = Product.order("RANDOM()").take 6
        @blogs = Blog.all.take(15)
    end
end

app/views/products/show.html.erb
<% provide :title, t('product.title') %>

<% content_for :banner do %>
  <!-- Breadcrumbs -->
  <div class="breadcrumbs">
    <div class="container">
      <ul>
        <li><%= link_to t('home_pages.title'), root_path, title: t('go_to_home') %></li><span>&raquo;</span>
        <li><%= link_to @product.category.title, category_path(@product.category), title: t('go_to_category') %></li><span>&raquo;</span>
        <li><%= @product.name %></li>
      </ul>
    </div>
  </div>
  <!-- Breadcrumbs End --> 
<% end %>

<% content_for :content do %>
  <div class="product-detail pb-3">
    <div class="container">
      <h1 class="mt-3 mb-3"><%= @product.name %></h1>
      <div class="product-intro">
        <div class="row">
          <div class="col-sm-6 col-12">
            <div class="grid images_3_of_2">

              <!-- .gallery-slider -->
              <div class="gallery-slider">

                <!-- __images -->
                <div class="gallery-slider__images">
                  <div>
                    <% @product.images.each do |image| %>
                      <!-- .item -->
                      <div class="item">
                        <div class="img-fill">
                          <%= image_tag image.url, alt: "Product image" %>
                        </div>
                      </div>
                      <!-- /.item -->
                    <% end %>
                  </div>
                  <button class="prev-arrow slick-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 1792">
                      <path fill="#fff" d="M1171 301L640 832l531 531q19 19 19 45t-19 45l-166 166q-19 19-45 19t-45-19L173 877q-19-19-19-45t19-45L915 45q19-19 45-19t45 19l166 166q19 19 19 45t-19 45z" />
                    </svg>
                  </button>
                  <button class="next-arrow slick-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 1792">
                      <path fill="#fff" d="M1107 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45L275 45q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z" />
                    </svg>
                  </button>
                </div>
                <!-- /__images -->


                <!-- __thumbnails -->
                <div class="gallery-slider__thumbnails">
                  <div>
                    <% @product.images.each do |image| %>
                      <!-- .item -->
                      <div class="item">
                        <div class="img-fill">
                          <%= image_tag image.url, alt: "Product image" %>
                        </div>
                      </div>
                      <!-- /.item -->
                    <% end %>
                  </div>

                  <button class="prev-arrow slick-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 1792">
                      <path fill="#fff" d="M1171 301L640 832l531 531q19 19 19 45t-19 45l-166 166q-19 19-45 19t-45-19L173 877q-19-19-19-45t19-45L915 45q19-19 45-19t45 19l166 166q19 19 19 45t-19 45z" />
                    </svg>
                  </button>
                  <button class="next-arrow slick-arrow">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 1792">
                      <path fill="#fff" d="M1107 877l-742 742q-19 19-45 19t-45-19l-166-166q-19-19-19-45t19-45l531-531-531-531q-19-19-19-45t19-45L275 45q19-19 45-19t45 19l742 742q19 19 19 45t-19 45z" />
                    </svg>
                  </button>
                </div>
                <!-- /__thumbnails -->

              </div>
              <!-- /.gallery-slider -->

            </div>
          </div>
          <div class="col-sm-6 col-12">
            <div class="description">
              <h5><%= @product.description.html_safe %></h5>
              <% if @product.sale_off > 0 %>
                <h5>
                  <%= t 'product.expired_date' %>: <span class="expired"><%= @product.expired_date.strftime("%d/%m/%Y") %></span>
                </h5>
              <% end %>
              <% if @product.get_saleoff_price != 0 %>
                <p>
                  <span class="item_price"><%= number_to_currency @product.get_saleoff_price %></span>
                  <del><%= number_to_currency @product.price if @product.sale_off > 0 %></del>
                </p>
              <% else %>
                <p class="zero-price">Liên hệ</p>
              <% end %>
              <div class="mt-2">
                <button 
                  class="btn btn-primary add-cart-btn"
                  data-name="<%= @product.name %>"
                  data-price="<%= @product.get_saleoff_price %>"
                  data-image="<%= @product.images[0].url %>">
                    Thêm vào giỏ hàng
                </button>
              </div>
            </div>
          </div>
        </div>
        
        <div class="function mt-4">
          <h3 class="mb-3">
            Giới thiệu
            <div class="line"></div>
          </h3>
          <%= @product.information.html_safe %>
        </div>
      </div>

      <div class="blog-list mt-4">
        <h1 class="mb-3">
          <%= link_to t('home_pages.project'), blogs_path %>
        </h1>
        <div class="project">
          <% @blogs.each do |blog| %>
            <div class="cards">
              <div class="card-item">
                <%= link_to blog_path(blog), title: blog.title do %>
                  <div class="card-image" style="background-image: url(<%= blog.image.url %>)">
                  </div>
                <% end %>
                <div class="card-info">
                  <%= link_to blog_path(blog), title: blog.title do %>
                    <h2 class="card-title"><%= blog.title %></h2>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>