config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#index"
  get "/about", to: "pages#about"
  get "/cart", to: "pages#cart"
  get "/care", to: "pages#care"
  patch "/order", to: "pages#order"
  get "/thankyou", to: "pages#thankyou"
  resources :categories
  resources :products
  resources :blogs
  resources :instructions

  # admin side
  namespace :admin do
    root to: "admin#index"
    resources :products
    resources :categories
    resources :users, only: [:index]
    resources :banners
    resources :videos
    resources :blogs
    resources :instructions
  end
  
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::AdminController
  before_action :set_video, only: [:edit, :update, :destroy]
  
  def index
      @videos = Video.paginate(:page => params[:page], :per_page => 10)
  end

  def new 
      @video = Video.new
  end

  def create
      @video = Video.new video_params
      if @video.save
          flash[:success] = "Created successfully!!"
          redirect_to admin_videos_path
      else
          render :new
      end
  end

  def edit
  end

  def update
    if @video.update_attributes video_params
      flash[:success] = "Updated!!"
      redirect_to admin_videos_path
    else
      render :edit
    end
  end

  def destroy
      if @video.destroy
          flash[:success] = "Deleted!!"
          redirect_to admin_videos_path
      end
  end

  private
  def video_params
      params.require(:video).permit(:youtube_link, :image)
  end

  def set_video
      @video = Video.find params[:id]
  end
end

app/views/admin/videos/_form.html.erb
<%= form_for [:admin, @video] do |f| %>
  <%= @video.errors.full_messages.first if @video.errors.any? %>

  <div class="form-group">
    <%= f.label :youtube_link %>
    <%= f.text_field :youtube_link, size: 60 %>
  </div>

  <div class="form-group">
    <%= f.label :image_cover %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <%= link_to "Back", :back, class: "btn btn-primary" %>
<% end %>

app/views/admin/videos/edit.html.erb
<% provide :title, "Edit video" %>
<% provide :button_text, "Update" %>

<%= content_for :content do %>
    <h1>Edit video</h1>
    <%= render 'form' %>
<% end %>

app/views/admin/videos/index.html.erb
<% content_for :content do %>
    <div style="padding-top: 10px">
        <%= link_to "Add new video", new_admin_video_path, class: "btn btn-primary" %>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Youtube link</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <% @videos.each do |video| %>
                <tr>
                    <td><%= video.id %></td>
                    <td><%= link_to video.youtube_link, video.youtube_link %></td>
                    <td>
                        <%= link_to edit_admin_video_path(video), class:"btn btn-primary btn-sm" do %>
                          <span class="fa fa-pencil"></span>
                          Edit
                      <% end %>
                      <%= link_to admin_video_path(video), data: { confirm: "Are you sure?" }, method: :delete, class:"btn btn-danger btn-sm" do %>
                          <span class="fa fa-trash"></span>
                          Delete
                      <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= will_paginate @videos %>
<% end %>

app/views/admin/videos/new.html.erb
<% provide :title, "Create new video" %>
<% provide :button_text, "Create" %>

<%= content_for :content do %>
    <h1>Create new video</h1>
    <%= render 'form' %>
<% end %>